# Site settings
title: Slamlab - Events
description: Slamlab - Events
baseurl: "/events" # the subpath of your site, e.g. /blog
url: "https://slam.phil.hhu.de" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Slamlab
user_description: Events page for Slamlab
email: slamlab@hhu.de
twitter_username: SLaMLab_HHU
github_username: hhuslamlab 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
